server:
  port: 8029

spring:
  application:
    name: erp-core
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  datasource:
    url: jdbc:mysql://localhost:3306/erp_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 16   # ğŸ‘ˆ å¿…é¡» â‰¥ ä½ çš„ exportExecutor çº¿ç¨‹æ•°
      minimum-idle: 4         # å¯é€‰ï¼šä¿æŒå°‘é‡ç©ºé—²è¿æ¥
      connection-timeout: 30000
  jpa:
    hibernate:
      # åœ¨ç¬¬ä¸€æ¬¡è¿è¡Œæ—¶è‡ªåŠ¨åˆ›å»ºè¡¨ï¼Œä¹‹åå»ºè®®æ”¹ä¸º 'none' æˆ– 'validate'
      ddl-auto: update
    show-sql: true # å¼€å‘æ—¶æ˜¾ç¤ºSQLè¯­å¥
    properties:
      hibernate:
        format_sql: true # æ ¼å¼åŒ–SQLè¾“å‡º
    #é…ç½®rabbitMq æœåŠ¡å™¨
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root

payroll:
  dispatch:
    cron: "0/20 * * * * ?"   # æœ¬åœ°æ¯20ç§’è·‘ä¸€æ¬¡ï¼ˆä¼šè¢« prod è¦†ç›–ï¼‰
  reconcile:
    cron: "0/40 * * * * ?"   # æœ¬åœ°æ¯40ç§’è·‘ä¸€æ¬¡ï¼ˆä¼šè¢« prod è¦†ç›–ï¼‰
