server:
  port: 8039

spring:
  application:
    name: bank-channel-service
    #é…ç½®rabbitMq æœåŠ¡å™¨
  rabbitmq:
    listener:
      simple:
        concurrency: 1          # â† å…³é”®ï¼åªå¼€ 1 ä¸ªæ¶ˆè´¹è€…çº¿ç¨‹
        max-concurrency: 1
#        retry:
#          enabled: true
#          max-attempts: 4  # æ€»å…±å°è¯•4æ¬¡ï¼ˆ1æ¬¡åŸå§‹ + 3æ¬¡é‡è¯•ï¼‰
        default-requeue-rejected: false  # å¤±è´¥ä¸ requeueï¼Œèµ° DLQ
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
  datasource:
    url: jdbc:mysql://localhost:3306/erp_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 16   # ğŸ‘ˆ å¿…é¡» â‰¥ ä½ çš„ exportExecutor çº¿ç¨‹æ•°
      minimum-idle: 4         # å¯é€‰ï¼šä¿æŒå°‘é‡ç©ºé—²è¿æ¥
      connection-timeout: 30000
  jpa:
    hibernate:
      # åœ¨ç¬¬ä¸€æ¬¡è¿è¡Œæ—¶è‡ªåŠ¨åˆ›å»ºè¡¨ï¼Œä¹‹åå»ºè®®æ”¹ä¸º 'none' æˆ– 'validate'
      ddl-auto: update
    show-sql: true # å¼€å‘æ—¶æ˜¾ç¤ºSQLè¯­å¥
    properties:
      hibernate:
        format_sql: true # æ ¼å¼åŒ–SQLè¾“å‡º
    #é…ç½®rabbitMq æœåŠ¡å™¨